export const toolsRegistry = [
  {
    id: "minecraft-whitelist-command-generator",
    category: "Minecraft",
    title: "Minecraft Whitelist Command Generator",
    description:
      "Generate whitelist, op, deop, ban, pardon, and kick commands for Minecraft servers.",
    path: "/tools/minecraft-whitelist-command-generator",
    status: "live",
    image: "/images/tools/minecraft-whitelist.jpg",
    icon: "⚔️",
    accentColor: "#10b981",
    tags: ["minecraft", "whitelist", "commands", "server admin"],
    isPopular: true,
    relatedToolIds: ["minecraft-server-properties-generator", "minecraft-motd-generator", "minecraft-server-rules-generator", "minecraft-lfg-post-generator", "minecraft-whitelist-application-generator"],
  },
  {
    id: "minecraft-whitelist-application-generator",
    category: "Minecraft",
    title: "Minecraft Whitelist Application Generator",
    description: "Generate whitelist application forms, Discord templates, player screening questions, staff checklists, and approval messages for Minecraft servers.",
    path: "/tools/minecraft-whitelist-application-generator",
    status: "live",
    tags: ["minecraft", "whitelist", "application", "discord form", "smp", "server admin"],
    isPopular: false,
    image: "/images/tools/minecraft-whitelist-application.jpg",
    icon: "📝",
    accentColor: "#10b981",
    relatedToolIds: ["minecraft-whitelist-command-generator", "minecraft-server-rules-generator", "minecraft-lfg-post-generator", "minecraft-motd-generator"],
  },
  {
    id: "minecraft-motd-generator",
    category: "Minecraft",
    title: "Minecraft MOTD Generator",
    description: "Generate Minecraft MOTDs, server descriptions, color-code friendly server list text, Discord welcome messages, and short promotional text for Minecraft servers.",
    path: "/tools/minecraft-motd-generator",
    status: "live",
    tags: ["minecraft", "motd", "server description", "server list", "discord welcome"],
    isPopular: false,
    image: "/images/tools/minecraft-motd.jpg",
    icon: "\u{1F4DD}",
    accentColor: "#10b981",
    relatedToolIds: ["minecraft-server-properties-generator", "minecraft-server-rules-generator", "minecraft-whitelist-command-generator", "minecraft-lfg-post-generator", "minecraft-whitelist-application-generator"],
  },
  {
    id: "minecraft-server-rules-generator",
    category: "Minecraft",
    title: "Minecraft Server Rules Generator",
    description:
      "Generate clear server rules for SMP, whitelist, PvE, and community survival servers.",
    path: "/tools/minecraft-server-rules-generator",
    status: "live",
    image: "/images/tools/minecraft-rules.jpg",
    icon: "📜",
    accentColor: "#10b981",
    tags: ["minecraft", "rules", "server admin", "community"],
    isPopular: false,
    relatedToolIds: ["minecraft-server-properties-generator", "minecraft-motd-generator", "minecraft-whitelist-command-generator", "minecraft-lfg-post-generator", "minecraft-whitelist-application-generator"],
  },
  {
    id: "minecraft-server-properties-generator",
    category: "Minecraft",
    title: "Minecraft server.properties Generator",
    description:
      "Generate clean server.properties settings for Minecraft Java servers, including survival SMPs, whitelist servers, PvE worlds, and private servers.",
    path: "/tools/minecraft-server-properties-generator",
    status: "live",
    image: "/images/tools/minecraft-server-properties.jpg",
    icon: "\u{2699}\uFE0F",
    accentColor: "#10b981",
    tags: ["minecraft", "server.properties", "server config", "smp", "whitelist", "java edition"],
    isPopular: true,
    relatedToolIds: ["minecraft-motd-generator", "minecraft-server-rules-generator", "minecraft-whitelist-command-generator", "minecraft-lfg-post-generator", "minecraft-whitelist-application-generator"],
  },
  {
    id: "minecraft-lfg-post-generator",
    category: "Minecraft",
    title: "Minecraft LFG Post Generator",
    description:
      "Generate Minecraft LFG posts for Reddit, Discord, SMPs, whitelist survival servers, and small Minecraft communities.",
    path: "/tools/minecraft-lfg-post-generator",
    status: "live",
    image: "/images/tools/minecraft-lfg-post.jpg",
    icon: "\u{1F50D}",
    accentColor: "#10b981",
    tags: ["minecraft", "lfg", "recruitment", "discord", "reddit", "smp"],
    isPopular: false,
    relatedToolIds: ["minecraft-whitelist-command-generator", "minecraft-whitelist-application-generator", "minecraft-motd-generator", "minecraft-server-rules-generator", "minecraft-server-properties-generator", "discord-announcement-generator"],
  },
  {
    id: "discord-announcement-generator",
    category: "Discord",
    title: "Discord Announcement Generator",
    description:
      "Generate polished Discord announcements for gaming communities, server launches, maintenance notices, events, and updates.",
    path: "/tools/discord-announcement-generator",
    status: "live",
    image: "/images/tools/discord-announcement.jpg",
    icon: "💬",
    accentColor: "#6366f1",
    tags: ["discord", "announcements", "community", "notifications"],
    isPopular: true,
    relatedToolIds: [
      "server-maintenance-message-generator",
      "minecraft-lfg-post-generator",
      "minecraft-whitelist-command-generator",
      "discord-rules-generator",
    ],
  },
  {
    id: "discord-rules-generator",
    category: "Discord",
    title: "Discord Rules Generator",
    description: "Generate clear Discord rules for gaming communities, survival servers, roleplay groups, private servers, and community hubs.",
    path: "/tools/discord-rules-generator",
    status: "live",
    tags: ["discord", "server rules", "community", "gaming", "moderation"],
    isPopular: false,
    image: "/images/tools/discord-rules.jpg",
    icon: "📜",
    accentColor: "#6366f1",
    relatedToolIds: [
      "discord-announcement-generator",
      "server-maintenance-message-generator",
      "minecraft-server-rules-generator",
      "valheim-server-rules-generator",
    ],
  },
  {
    id: "discord-welcome-message-generator",
    category: "Discord",
    title: "Discord Welcome Message Generator",
    description: "Generate Discord welcome messages, onboarding posts, role-selection instructions, pinned messages, and new member guidance for gaming communities and private servers.",
    path: "/tools/discord-welcome-message-generator",
    status: "live",
    tags: ["discord", "welcome", "onboarding", "community", "new members", "roles"],
    isPopular: false,
    image: "/images/tools/discord-welcome.jpg",
    icon: "\u{1F44B}",
    accentColor: "#6366f1",
    relatedToolIds: [
      "discord-announcement-generator",
      "discord-rules-generator",
      "server-maintenance-message-generator",
      "minecraft-lfg-post-generator",
    ],
  },
  {
    id: "server-maintenance-message-generator",
    category: "Server Admin",
    title: "Server Maintenance Message Generator",
    description:
      "Generate maintenance notices, restart warnings, downtime updates, and in-game warning messages for game servers.",
    path: "/tools/server-maintenance-message-generator",
    status: "live",
    image: "/images/tools/server-maintenance.jpg",
    icon: "🔧",
    accentColor: "#3b82f6",
    tags: ["server admin", "maintenance", "downtime", "warnings"],
    isPopular: true,
    relatedToolIds: [
      "discord-announcement-generator",
      "project-zomboid-mod-list-formatter",
      "valheim-admin-command-helper",
      "server-status-message-generator",
    ],
  },
  {
    id: "server-status-message-generator",
    category: "Server Admin",
    title: "Server Status Message Generator",
    description: "Generate clear online, offline, maintenance, degraded performance, restart, and back-online status messages for game servers.",
    path: "/tools/server-status-message-generator",
    status: "live",
    tags: ["server status", "maintenance", "downtime", "discord", "server admin", "announcement"],
    isPopular: false,
    image: "/images/tools/server-status.jpg",
    icon: "\u{1F4E1}",
    accentColor: "#3b82f6",
    relatedToolIds: [
      "server-maintenance-message-generator",
      "discord-announcement-generator",
      "discord-rules-generator",
      "project-zomboid-admin-message-generator",
      "valheim-server-rules-generator",
    ],
  },
  {
    id: "project-zomboid-admin-message-generator",
    category: "Project Zomboid",
    title: "Project Zomboid Admin Message Generator",
    description:
      "Generate restart warnings, maintenance notices, rule reminders, whitelist messages, and community announcements for Project Zomboid servers.",
    path: "/tools/project-zomboid-admin-message-generator",
    status: "live",
    image: "/images/tools/project-zomboid-admin-messages.jpg",
    icon: "\u{1F9DF}",
    accentColor: "#e11d48",
    tags: ["project zomboid", "admin messages", "restart warning", "maintenance", "server admin", "community"],
    isPopular: false,
    relatedToolIds: ["project-zomboid-server-settings-helper", "project-zomboid-mod-list-formatter", "server-maintenance-message-generator", "discord-announcement-generator"],
  },
  {
    id: "project-zomboid-mod-list-formatter",
    category: "Project Zomboid",
    title: "Project Zomboid Mod List Formatter",
    description:
      "Format WorkshopItems, Mods, and Map lines for Project Zomboid servertest.ini files.",
    path: "/tools/project-zomboid-mod-list-formatter",
    status: "live",
    image: "/images/tools/project-zomboid-mods.jpg",
    icon: "🧟",
    accentColor: "#e11d48",
    tags: ["project zomboid", "mods", "workshop", "servertest.ini"],
    isPopular: false,
    relatedToolIds: [
      "server-maintenance-message-generator",
      "discord-announcement-generator",
      "minecraft-whitelist-command-generator",
    ],
  },
  {
    id: "project-zomboid-server-settings-helper",
    category: "Project Zomboid",
    title: "Project Zomboid Server Settings Helper",
    description:
      "Generate and understand common Project Zomboid servertest.ini settings for PvE, PvP, whitelist, safehouses, factions, chat, sleep, and long-term servers.",
    path: "/tools/project-zomboid-server-settings-helper",
    status: "live",
    image: "/images/tools/project-zomboid-settings.jpg",
    icon: "⚙️",
    accentColor: "#e11d48",
    tags: ["project zomboid", "server settings", "servertest.ini", "admin"],
    isPopular: true,
    relatedToolIds: [
      "project-zomboid-admin-message-generator",
      "project-zomboid-mod-list-formatter",
      "server-maintenance-message-generator",
      "minecraft-server-rules-generator",
    ],
  },
  {
    id: "project-zomboid-safehouse-rules-generator",
    category: "Project Zomboid",
    title: "Project Zomboid Safehouse Rules Generator",
    description: "Generate safehouse rules, base claim policies, faction rules, abandoned base cleanup rules, and dispute templates for Project Zomboid servers.",
    path: "/tools/project-zomboid-safehouse-rules-generator",
    status: "live",
    tags: ["project zomboid", "safehouse", "base claim", "factions", "pvp", "server rules"],
    isPopular: false,
    image: "/images/tools/project-zomboid-safehouse-rules.jpg",
    icon: "\u{1F3DA}\uFE0F",
    accentColor: "#e11d48",
    relatedToolIds: [
      "project-zomboid-server-settings-helper",
      "project-zomboid-admin-message-generator",
      "project-zomboid-mod-list-formatter",
      "server-status-message-generator",
    ],
  },
  {
    id: "valheim-server-rules-generator",
    category: "Valheim",
    title: "Valheim Server Rules Generator",
    description:
      "Generate clear Valheim server rules for co-op realms, modded servers, progression control, wards, portals, and community builds.",
    path: "/tools/valheim-server-rules-generator",
    status: "live",
    image: "/images/tools/valheim-rules.jpg",
    icon: "\u{1F6E1}\uFE0F",
    accentColor: "#f59e0b",
    tags: ["valheim", "server rules", "co-op", "progression", "wards", "community"],
    isPopular: false,
    relatedToolIds: ["valheim-admin-command-helper", "server-maintenance-message-generator", "discord-announcement-generator", "minecraft-server-rules-generator"],
  },
  {
    id: "valheim-event-announcement-generator",
    category: "Valheim",
    title: "Valheim Event Announcement Generator",
    description: "Generate event announcements for Valheim boss fights, community builds, exploration nights, trading days, progression votes, and Viking server events.",
    path: "/tools/valheim-event-announcement-generator",
    status: "live",
    tags: ["valheim", "event announcement", "boss fight", "community build", "progression", "discord"],
    isPopular: false,
    image: "/images/tools/valheim-event-announcement.jpg",
    icon: "\u{1F525}",
    accentColor: "#f59e0b",
    relatedToolIds: [
      "valheim-server-rules-generator",
      "valheim-admin-command-helper",
      "discord-announcement-generator",
      "server-status-message-generator",
    ],
  },
  {
    id: "icarus-server-rules-generator",
    category: "ICARUS",
    title: "ICARUS Server Rules Generator",
    description: "Generate rules for ICARUS co-op survival worlds, persistent servers, shared bases, missions, mounts, resources, and long-term communities.",
    path: "/tools/icarus-server-rules-generator",
    status: "live",
    tags: ["icarus", "server rules", "co-op", "survival", "missions", "persistent world"],
    isPopular: false,
    image: "/images/tools/icarus-server-rules.jpg",
    icon: "\u{1F680}",
    accentColor: "#06b6d4",
    relatedToolIds: [
      "server-maintenance-message-generator",
      "server-status-message-generator",
      "discord-announcement-generator",
      "valheim-server-rules-generator",
    ],
  },
  {
    id: "7-days-to-die-server-rules-generator",
    category: "7 Days to Die",
    title: "7 Days to Die Server Rules Generator",
    description: "Generate rules for 7DTD PvE, PvP, horde night, base claims, traders, vehicles, wipes, and long-term apocalypse communities.",
    path: "/tools/7-days-to-die-server-rules-generator",
    status: "live",
    tags: ["7 days to die", "7dtd", "server rules", "pve", "pvp", "horde night", "base claims"],
    isPopular: false,
    image: "/images/tools/7-days-to-die-server-rules.jpg",
    icon: "\u{1F9DF}\u200D\u2642\uFE0F",
    accentColor: "#f97316",
    relatedToolIds: [
      "server-maintenance-message-generator",
      "server-status-message-generator",
      "discord-announcement-generator",
      "icarus-server-rules-generator",
    ],
  },
  {
    id: "valheim-admin-command-helper",
    category: "Valheim",
    title: "Valheim Admin Command Helper",
    description:
      "Search, understand, and copy useful Valheim admin, moderation, debug, teleport, map, and spawn commands.",
    path: "/tools/valheim-admin-command-helper",
    status: "live",
    image: "/images/tools/valheim-admin.jpg",
    icon: "\u{1F6E1}\uFE0F",
    accentColor: "#f59e0b",
    tags: ["valheim", "admin commands", "server admin", "moderation", "debug", "teleport", "spawn"],
    isPopular: true,
    relatedToolIds: [
      "valheim-server-rules-generator",
      "server-maintenance-message-generator",
      "discord-announcement-generator",
      "project-zomboid-mod-list-formatter",
      "minecraft-server-rules-generator",
    ],
  },
];

export const CATEGORIES = [
  "Minecraft",
  "Discord",
  "Server Admin",
  "Project Zomboid",
  "Valheim",
  "ICARUS",
  "7 Days to Die",
];

export const CATEGORY_COLORS = {
  Minecraft: "#10b981",
  Discord: "#6366f1",
  "Server Admin": "#3b82f6",
  "Project Zomboid": "#e11d48",
  Valheim: "#f59e0b",
  ICARUS: "#06b6d4",
  "7 Days to Die": "#f97316",
};

export const CATEGORY_ICONS = {
  Minecraft: "⚔️",
  Discord: "💬",
  "Server Admin": "🔧",
  "Project Zomboid": "🧟",
  Valheim: "🛡️",
  ICARUS: "🌍",
  "7 Days to Die": "🧱",
};

export function getRelatedTools(toolId, limit = 4) {
  const tool = toolsRegistry.find((t) => t.id === toolId);
  if (!tool) return [];
  return toolsRegistry
    .filter(
      (t) => tool.relatedToolIds?.includes(t.id) && t.status === "live",
    )
    .slice(0, limit);
}
